apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: itaycolors.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                itay_color:
                  type: string
  scope: Namespaced
  names:
    plural: itaycolors
    singular: itaycolor
    kind: ItayColor
    shortNames:
      - ic
